language: C

# running as root enables a few extra tests

before_script:
  - "sudo apt-get install cmake"
  - "mkdir build && cd build"
  - "RUN_ROOT_TESTS=1 cmake .."
  - "make"

script:
  - "./interface/test/TUNInterface_ipv6_root_test"
  - "./interface/test/TUNInterface_ipv4_root_test"
  - "sudo make test"
