language: C

# running as root enables a few extra tests
before_script:
  - "sudo apt-get install cmake"
  - "mkdir build && cd build"
  - "sudo bash -c 'RUN_ROOT_TESTS=1 cmake .. && make'"

script:
  - "sudo make test"
