language: C

before_script:
  - "sudo apt-get install cmake"
  - "mkdir build && cd build"
  - "cmake .."
  - "make"

script:
  - "[ ! -d /dev/net ] && echo 'creating /dev/net' && sudo mkdir /dev/net"
  - "[ ! -c /dev/net/tun ] && echo 'creating /dev/net/tun' && sudo mknod /dev/net/tun c 10 200"
  - "cat /dev/net/tun"
  - "sudo make test"
