language: C

# running as root enables a few extra tests

before_script:
  - "sudo apt-get install cmake"
  - "mkdir build && cd build"
  - "sudo RUN_ROOT_TESTS=1 cmake .."
  - "sudo make"

script:
  - "sudo make test"
